<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android34.0</TargetFramework>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <ApplicationId>com.tomize.deezerrpc</ApplicationId>
    <ApplicationTitle>DeezerRPC</ApplicationTitle>
    <ApplicationVersion>23</ApplicationVersion>
    <ApplicationDisplayVersion>1.1.22</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AndroidLinkMode>SdkOnly</AndroidLinkMode>
    <DefaultItemExcludes>$(DefaultItemExcludes);native\build\**;native\build-ninja\**;native\prebuilt\**;native\prebuilt-full\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeezerRpc.Core\DeezerRpc.Core.csproj" />
    <PackageReference Include="Xamarin.AndroidX.Browser" Version="1.8.0.11" />
  </ItemGroup>
  <ItemGroup Condition="Exists('..\..\vendor\discord-social-sdk\lib\release\discord_partner_sdk.aar')">
    <AndroidNativeLibrary Include="native\prebuilt-full\**\libdeezerrpc_discord_bridge.so" />
    <AndroidLibrary Include="..\..\vendor\discord-social-sdk\lib\release\discord_partner_sdk.aar" Bind="false" />
  </ItemGroup>
</Project>
