<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android34.0</TargetFramework>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <ApplicationId>com.tomize.deezerrpc</ApplicationId>
    <ApplicationTitle>DeezerRPC</ApplicationTitle>
    <ApplicationVersion>13</ApplicationVersion>
    <ApplicationDisplayVersion>1.1.12</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AndroidLinkMode>SdkOnly</AndroidLinkMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeezerRpc.Core\DeezerRpc.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AndroidNativeLibrary Remove="native\prebuilt\**\*.so" />
    <AndroidNativeLibrary Remove="native\prebuilt-full\**\libdiscord_partner_sdk.so" />
  </ItemGroup>
  <ItemGroup Condition="Exists('..\..\vendor\discord-social-sdk\lib\release\discord_partner_sdk.aar')">
    <AndroidLibrary Include="..\..\vendor\discord-social-sdk\lib\release\discord_partner_sdk.aar" Bind="false" />
  </ItemGroup>
</Project>
